defaults: &defaults
  encoding: utf8
  adapter: mysql2
  host: localhost
  username: root
  password: 123456
  database: demo_napa_development

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
